apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-streams
  namespace: openshift-operators
spec:
  channel: amq-streams-2.2.x
  name: amq-streams
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: FIPS_MODE
        value: disabled
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-registry
  namespace: openshift-operators
spec:
  channel: 2.x
  name: service-registry-operator
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
