apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-registry-pgsql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: my-registry-pgsql-env
type: Opaque
stringData:
  POSTGRESQL_DATABASE: registry
  POSTGRESQL_USER: admin
  POSTGRESQL_PASSWORD: changeit
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-registry-pgsql
spec:
  replicas: 1
  serviceName: postgres
  selector:
    matchLabels:
      app: my-registry-pgsql
  template:
    metadata:
      labels:
        app: my-registry-pgsql
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel8/postgresql-12
          resources:
            limits:
              memory: 1Gi
          envFrom:
            - secretRef:
                name: my-registry-pgsql-env
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: my-registry-pgsql-data
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command: [ "psql", "template1", "-c", "SELECT 1" ]
            initialDelaySeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: [ "psql", "template1", "-c", "SELECT 1" ]
            initialDelaySeconds: 60
            timeoutSeconds: 10
      volumes:
        - name: my-registry-pgsql-data
          persistentVolumeClaim:
            claimName: my-registry-pgsql-data
---
apiVersion: v1
kind: Service
metadata:
  name: my-registry-pgsql-svc
spec:
  ports:
    - name: pgsql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: my-registry-pgsql
