apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: my-registry
spec:
  configuration:
    persistence: sql
    sql:
      dataSource:
        url: "jdbc:postgresql://my-registry-pgsql-svc:5432/registry"
        userName: "admin"
        password: "changeit"
