apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-operators
  namespace: test
spec:
  targetNamespaces:
    - test
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-registry
  namespace: openshift-operators
spec:
  channel: 2.x
  name: service-registry-operator
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
