apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-operators
  namespace: test
spec:
  targetNamespaces:
    - test
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-streams
  namespace: openshift-operators
spec:
  channel: amq-streams-2.2.x
  name: amq-streams
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: FIPS_MODE
        value: disabled
