apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster-tgt
spec:
  kafka:
    replicas: 3
    version: 3.1.0
    config:
      inter.broker.protocol.version: "3.1"
      num.partitions: 3
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      min.insync.replicas: 2
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    jmxOptions: { }
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
    jvmOptions:
      gcLoggingEnabled: false
    storage:
      size: 10Gi
      type: persistent-claim
      deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    template:
      pod:
        terminationGracePeriodSeconds: 60
  zookeeper:
    replicas: 3
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
    jvmOptions:
      gcLoggingEnabled: false
    storage:
      size: 5Gi
      type: persistent-claim
      deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
    userOperator:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
